version: '3.8'
services:
  factorio:
    image: factoriotools/factorio:stable
    environment:
      - RCON_PASSWORD=${RCON_PASSWORD}
    volumes:
      - factorio-data:/factorio
    expose:
      - "27015"
    networks:
      - internal

  dashboard:
    build: .
    depends_on:
      - factorio
    env_file: .env
    volumes:
      - factorio-data:/factorio:ro
    ports:
      - "3000:3000"
    networks:
      - internal

  caddy:
    image: caddy:2
    depends_on:
      - dashboard
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    networks:
      - internal

volumes:
  factorio-data:
  caddy-data:
  caddy-config:

networks:
  internal:
    driver: bridge
